# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_info', '0002_auto_20190303_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
