# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_info', '0004_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='link',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
