# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_info', '0005_sponsors_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsors',
        ),
    ]
