# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_info', '0006_delete_sponsors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
