# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190307_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonmodel',
            name='challenge',
            field=models.CharField(choices=[(b'Beat-My-Code', b'Beat-My-Code'), (b'Smart GeekyNova', b'Smart GeekyNova'), (b'Full Stack Battle', b'Full Stack Battle')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
