# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190310_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunGamesModel',
            new_name='MyPageantryModel',
        ),
        migrations.AlterModelOptions(
            name='mypageantrymodel',
            options={'verbose_name': 'My Pageantry', 'verbose_name_plural': 'My Pageantry'},
        ),
    ]
