# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190311_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintballmodel',
            name='teamName',
        ),
    ]
