# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_paintballmodel_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintballmodel',
            name='firstPlayer',
            field=models.CharField(default='name', max_length=75),
            preserve_default=False,
        ),
    ]
